# Generated by Django 5.2.17 on 2026-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_unique_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
